FROM debian:latest

RUN apt-get update
RUN apt-get install -y git vim net-tools iputils-ping openssh-server sudo build-essential libssl-dev g++ curl
RUN apt-get install -y npm 
RUN npm install prisma --save-dev
RUN npm install @prisma/client

RUN mkdir /devbox
ADD entry.sh /devbox
RUN chmod +x /devbox/entry.sh

ENTRYPOINT ["/devbox/entry.sh", "FOREGROUND"]